"""add_ranking_events_table

Revision ID: 420be6544bcb
Revises: 
Create Date: 2025-12-20 11:15:09.897750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '420be6544bcb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranking_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('prev_rank', sa.Integer(), nullable=True),
    sa.Column('curr_rank', sa.Integer(), nullable=True),
    sa.Column('rank_change', sa.Integer(), nullable=True),
    sa.Column('rank_change_pct', sa.Float(), nullable=True),
    sa.Column('prev_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('curr_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_change_pct', sa.Float(), nullable=True),
    sa.Column('prev_review_count', sa.Integer(), nullable=True),
    sa.Column('curr_review_count', sa.Integer(), nullable=True),
    sa.Column('review_change', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('context_collected', sa.Boolean(), nullable=True),
    sa.Column('insight_generated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['amazon_categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['amazon_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ranking_events')
    # ### end Alembic commands ###
