"""add_event_context_tables

Revision ID: 92180ff00da8
Revises: 420be6544bcb
Create Date: 2025-12-20 11:22:58.196705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92180ff00da8'
down_revision: Union[str, None] = '420be6544bcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_context_competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('competitor_product_id', sa.Integer(), nullable=True),
    sa.Column('competitor_rank', sa.Integer(), nullable=True),
    sa.Column('competitor_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('competitor_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('rank_change', sa.Integer(), nullable=True),
    sa.Column('price_change_pct', sa.Float(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competitor_product_id'], ['amazon_products.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['ranking_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_context_competitors_event_id'), 'event_context_competitors', ['event_id'], unique=False)
    op.create_table('event_context_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.String(length=255), nullable=True),
    sa.Column('reviewer_name', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('verified_purchase', sa.Boolean(), nullable=True),
    sa.Column('review_title', sa.Text(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=True),
    sa.Column('review_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['ranking_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_context_reviews_event_id'), 'event_context_reviews', ['event_id'], unique=False)
    op.create_table('event_context_social',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('content_id', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.Text(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('engagement_score', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_viral', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['ranking_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_context_social_event_id'), 'event_context_social', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_context_social_event_id'), table_name='event_context_social')
    op.drop_table('event_context_social')
    op.drop_index(op.f('ix_event_context_reviews_event_id'), table_name='event_context_reviews')
    op.drop_table('event_context_reviews')
    op.drop_index(op.f('ix_event_context_competitors_event_id'), table_name='event_context_competitors')
    op.drop_table('event_context_competitors')
    # ### end Alembic commands ###
